version: 0.0
os: linux
files:
  - source: /
    destination: /opt/kv-store
    file_exists_behavior: OVERWRITE
hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 300
runas: root
