version: '3'

services:
    web:
        build: .
        depends_on:
         - nats
        env_file: .env
        volumes:
          - ${PWD}/kvs.log:/kvs.log
        ports:
         - 80

    nats:
        image: nats:2.6.0-alpine
        ports:
         - "4222:4222"

    lb:
        image: dockercloud/haproxy
        links:
            - web
        ports:
            - 80:80
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
