version: '3'

services:
    web:
        build: .
        depends_on:
         - nats
        env_file: .env
        ports:
         - "8000:${PORT:-8000}"

    nats:
        image: nats:2.6.0-alpine
        ports:
         - "4222:4222"
