name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: sudo apt-get -qy update && sudo apt-get install -y libssl-dev libssl1.1
      - uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
      - uses: Swatinem/rust-cache@v1
      - name: Run tests and validate lockfile
        env:
          RUSTFLAGS: -D warnings
        run: cargo test --locked -- test-threads=1
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: sudo apt-get -qy update && sudo apt-get install -y libssl-dev libssl1.1
      - uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
      - uses: Swatinem/rust-cache@v1
      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: "0.18.0"
          args: " --avoid-cfg-tarpaulin --exclude-files target* **/client.rs  **/error.rs --out Lcov --all"
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./lcov.info
